"""add review sessions and proposed changes

Revision ID: b144781ac690
Revises: ee78c0dd5908
Create Date: 2026-04-17 22:26:36.411486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b144781ac690'
down_revision: Union[str, None] = 'ee78c0dd5908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
