"""
Prompt constants for the AI extraction and revision agents.

Centralised here so prompts can be versioned, tested, and updated
independently of the orchestration logic.
"""

SCHEMA_REFERENCE = """
## Database Schema — Exact Field Names and Types

### HOUSEHOLD  (one record per client family or individual)
  name                        String   Full legal household name.        e.g. "John and Jane Smith"
  annual_income               Float    Total gross annual income (USD).  e.g. 175000.0
  estimated_total_net_worth   Float    All assets minus liabilities.     e.g. 2500000.0
  estimated_liquid_net_worth  Float    Liquid/accessible assets only.    e.g. 800000.0
  tax_bracket                 String   Federal tax bracket.              e.g. "32%", "24%"
  risk_tolerance              String   Investment risk posture.          e.g. "Conservative", "Moderate", "Aggressive", "Conservative to Moderate"
  primary_investment_objective String  Main goal for the portfolio.      e.g. "Retirement", "Growth", "Income", "Capital Preservation"
  time_horizon                String   Investment timeline.              e.g. "10–15 years", "Long-term", "Short-term (under 5 years)"
  source_of_funds             String   Where money comes from.          e.g. "Employment", "Business sale", "Rental income"
  primary_use_of_funds        String   What money will be used for.     e.g. "Retirement, College planning, Estate planning"
  liquidity_needs             String   How much cash access is needed.  e.g. "Low", "Moderate", "High — funds needed within 2 years"
  account_decision_making     String   Who decides on accounts.         e.g. "Individual", "Joint", "Trust", "POA"

### MEMBER  (one record per person in the household)
  first_name                  String   Legal first name.  (REQUIRED)
  last_name                   String   Legal last name.   (REQUIRED)
  dob                         String   Date of birth.                    e.g. "1974-12-03", "December 3, 1974"
  phone                       String   Primary phone number.             e.g. "512-555-3847"
  email                       String   Email address.                    e.g. "john.doe@gmail.com"
  address                     String   Full mailing address.             e.g. "4821 West Lake Dr, Austin TX 78746"
  occupation                  String   Current job title.                e.g. "Vice President of Business Development"
  employer                    String   Current company.                  e.g. "Dell Technologies"
  marital_status              String   "Single" | "Married" | "Divorced" | "Widowed" | "Separated"

### ACCOUNT  (one record per financial account)
  account_type                String   Account category.  e.g. "401K", "Roth IRA", "Individual Stocks", "Real Estate", "529 Plan"
  custodian                   String   Broker or bank.    e.g. "Fidelity", "Vanguard", "Schwab", "Chase"
  account_number              String   Only if explicitly stated in the transcript
  account_value               Float    Current market value in USD — only if stated as a specific number
"""

ENTITY_RULES = """
## Entity Resolution Rules

### Updating an existing client (person already in the database)
  - entity_type = "household"  →  entity_id = the household id shown in the DB context below
  - entity_type = "member"     →  entity_id = the member id shown in the DB context below
  - entity_type = "account"    →  entity_id = the account id shown in the DB context below
  - CRITICAL: only propose a change when the new value DIFFERS from the current DB value.
    Do NOT propose setting risk_tolerance = "Moderate" if it already says "Moderate".

### Creating a new client (person NOT in the database)
  - entity_type = "new_household"  →  entity_id = null
  - entity_type = "new_member"     →  entity_id = null
  - entity_type = "new_account"    →  entity_id = null

### Grouping rule — CRITICAL
All field changes for the same person or account MUST share the exact same entity_label.
Example: every field for "Benjamin Thompson" must use entity_label = "Benjamin Thompson".
This is how the apply step groups multiple field proposals into a single DB record.

### Do NOT propose
  - Fields whose DB value already matches what the transcript says
  - Fields with no clear transcript evidence
  - Dollar amounts described vaguely ("substantial", "significant") — leave as null
  - SSN unless spoken out digit-by-digit and completely unambiguous
"""

WHISPER_GUIDANCE = """
## Whisper Transcription Artifacts to Watch For
The transcript was generated by OpenAI Whisper, which has known error patterns:
  - Numbers spoken digit-by-digit get hyphenated:  "78746" → "7-8-7-4-6",  "4821" → "48-21"
  - Email domains get phonetically mangled:         "@gmail.com" → "atgmail.com"
  - Names can be misheard when the speaker changes topic mid-sentence
  - Phone numbers spoken continuously may be split inconsistently

When you detect these patterns:
  - Propose the corrected, human-readable value  (fix "7-8-7-4-6" → "78746")
  - Set confidence ≤ 0.85 for any value with clear Whisper artifacts
  - Note the artifact in the reasoning field so the reviewer knows to verify with the client
"""
